//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TXTextControl.Words.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TXTextControl.Words.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add Comment....
        /// </summary>
        internal static string Item_Edit_Comments_AddComment_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Comments_AddComment_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Review Comments....
        /// </summary>
        internal static string Item_Edit_Comments_ReviewComments_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Comments_ReviewComments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co&amp;mments.
        /// </summary>
        internal static string Item_Edit_Comments_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string Item_Edit_Copy_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Copy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string Item_Edit_Cut_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Cut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;For {0}.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Add_ForCurrentUser_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForCurrentUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For &amp;Everyone.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Add_ForEveryone_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForEveryone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Add_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;For {0}.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Remove_ForCurrentUser_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForCurrentUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For &amp;Everyone.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Remove_ForEveryone_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForEveryone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Remove_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Editable Regions.
        /// </summary>
        internal static string Item_Edit_EditableRegions_Text {
            get {
                return ResourceManager.GetString("Item_Edit_EditableRegions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Find....
        /// </summary>
        internal static string Item_Edit_Find_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Find_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string Item_Edit_Paste_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Paste_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow &amp;Copy.
        /// </summary>
        internal static string Item_Edit_Permissions_AllowCopy_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow &amp;Editing Form Fields.
        /// </summary>
        internal static string Item_Edit_Permissions_AllowEditingFormFields_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowEditingFormFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow &amp;Formatting.
        /// </summary>
        internal static string Item_Edit_Permissions_AllowFormatting_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowFormatting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Formatting &amp;Styles.
        /// </summary>
        internal static string Item_Edit_Permissions_AllowFormattingStyles_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowFormattingStyles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow &amp;Printing.
        /// </summary>
        internal static string Item_Edit_Permissions_AllowPrinting_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_AllowPrinting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Read Only.
        /// </summary>
        internal static string Item_Edit_Permissions_ReadOnly_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_ReadOnly_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permi&amp;ssions.
        /// </summary>
        internal static string Item_Edit_Permissions_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Permissions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr&amp;otect Document.
        /// </summary>
        internal static string Item_Edit_ProtectDocument_Text {
            get {
                return ResourceManager.GetString("Item_Edit_ProtectDocument_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string Item_Edit_Redo_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Redo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep&amp;lace....
        /// </summary>
        internal static string Item_Edit_Replace_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Replace_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;All.
        /// </summary>
        internal static string Item_Edit_SelectAll_Text {
            get {
                return ResourceManager.GetString("Item_Edit_SelectAll_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string Item_Edit_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Review Tracked Changes....
        /// </summary>
        internal static string Item_Edit_TrackedChanges_ReviewTrackedChanges_Text {
            get {
                return ResourceManager.GetString("Item_Edit_TrackedChanges_ReviewTrackedChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trac&amp;ked Changes.
        /// </summary>
        internal static string Item_Edit_TrackedChanges_Text {
            get {
                return ResourceManager.GetString("Item_Edit_TrackedChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Track Changes.
        /// </summary>
        internal static string Item_Edit_TrackedChanges_TrackChanges_Text {
            get {
                return ResourceManager.GetString("Item_Edit_TrackedChanges_TrackChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string Item_Edit_Undo_Text {
            get {
                return ResourceManager.GetString("Item_Edit_Undo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Account Settings....
        /// </summary>
        internal static string Item_File_CurrentUser_AccountSettings_Text {
            get {
                return ResourceManager.GetString("Item_File_CurrentUser_AccountSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign &amp;Out.
        /// </summary>
        internal static string Item_File_CurrentUser_SignOut_Text {
            get {
                return ResourceManager.GetString("Item_File_CurrentUser_SignOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Item_File_CurrentUser_Text {
            get {
                return ResourceManager.GetString("Item_File_CurrentUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Item_File_Exit_Text {
            get {
                return ResourceManager.GetString("Item_File_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string Item_File_New_Text {
            get {
                return ResourceManager.GetString("Item_File_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open….
        /// </summary>
        internal static string Item_File_Open_Text {
            get {
                return ResourceManager.GetString("Item_File_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Se&amp;tup….
        /// </summary>
        internal static string Item_File_PageSetup_Text {
            get {
                return ResourceManager.GetString("Item_File_PageSetup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print....
        /// </summary>
        internal static string Item_File_Print_Text {
            get {
                return ResourceManager.GetString("Item_File_Print_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pre&amp;view....
        /// </summary>
        internal static string Item_File_PrintPreview_Text {
            get {
                return ResourceManager.GetString("Item_File_PrintPreview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print &amp;Quick.
        /// </summary>
        internal static string Item_File_PrintQuick_Text {
            get {
                return ResourceManager.GetString("Item_File_PrintQuick_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recent Files.
        /// </summary>
        internal static string Item_File_RecentFiles_Text {
            get {
                return ResourceManager.GetString("Item_File_RecentFiles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string Item_File_Save_Text {
            get {
                return ResourceManager.GetString("Item_File_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;As….
        /// </summary>
        internal static string Item_File_SaveAs_Text {
            get {
                return ResourceManager.GetString("Item_File_SaveAs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign &amp;In....
        /// </summary>
        internal static string Item_File_SignIn_Text {
            get {
                return ResourceManager.GetString("Item_File_SignIn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string Item_File_Text {
            get {
                return ResourceManager.GetString("Item_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Barcode....
        /// </summary>
        internal static string Item_Format_Barcode_Text {
            get {
                return ResourceManager.GetString("Item_Format_Barcode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boo&amp;kmark....
        /// </summary>
        internal static string Item_Format_Bookmark_Text {
            get {
                return ResourceManager.GetString("Item_Format_Bookmark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;1, 2, 3.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_ArabicNumbers_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_ArabicNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Structured &amp;List.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_AsStructuredList_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_AsStructuredList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B&amp;ullets.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_Bullets_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Bullets_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;A, B, C.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_CapitalLetters_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_CapitalLetters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Decrease Level.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_DecreaseLevel_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_DecreaseLevel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&amp;ncrease Level.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_IncreaseLevel_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_IncreaseLevel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a, &amp;b, c.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_Letters_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Letters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Properties....
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_Properties_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;I, II, III, IV.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_RomanNumbers_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_RomanNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i, ii, iii, i&amp;v.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets and &amp;Numbering.
        /// </summary>
        internal static string Item_Format_BulletsAndNumbering_Text {
            get {
                return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Character....
        /// </summary>
        internal static string Item_Format_Character_Text {
            get {
                return ResourceManager.GetString("Item_Format_Character_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colu&amp;mns....
        /// </summary>
        internal static string Item_Format_Columns_Text {
            get {
                return ResourceManager.GetString("Item_Format_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit....
        /// </summary>
        internal static string Item_Format_FormFields_Edit_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Form &amp;Validation.
        /// </summary>
        internal static string Item_Format_FormFields_EnableFormValidation_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_EnableFormValidation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Manage Conditional Instructions....
        /// </summary>
        internal static string Item_Format_FormFields_ManageConditionalInstructions_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_ManageConditionalInstructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Form Fields.
        /// </summary>
        internal static string Item_Format_FormFields_Text {
            get {
                return ResourceManager.GetString("Item_Format_FormFields_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Headers and Footers....
        /// </summary>
        internal static string Item_Format_HeadersAndFooters_Text {
            get {
                return ResourceManager.GetString("Item_Format_HeadersAndFooters_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hype&amp;rlink....
        /// </summary>
        internal static string Item_Format_Hyperlink_Text {
            get {
                return ResourceManager.GetString("Item_Format_Hyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Image....
        /// </summary>
        internal static string Item_Format_Image_Text {
            get {
                return ResourceManager.GetString("Item_Format_Image_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language....
        /// </summary>
        internal static string Item_Format_Language_Text {
            get {
                return ResourceManager.GetString("Item_Format_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Bor&amp;ders....
        /// </summary>
        internal static string Item_Format_PageBorders_Text {
            get {
                return ResourceManager.GetString("Item_Format_PageBorders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page C&amp;olor....
        /// </summary>
        internal static string Item_Format_PageColor_Text {
            get {
                return ResourceManager.GetString("Item_Format_PageColor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page N&amp;umber....
        /// </summary>
        internal static string Item_Format_PageNumberField_Text {
            get {
                return ResourceManager.GetString("Item_Format_PageNumberField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paragraph....
        /// </summary>
        internal static string Item_Format_Paragraph_Text {
            get {
                return ResourceManager.GetString("Item_Format_Paragraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Body Text.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add to Paragraph.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_AddToParagraph_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Body Text.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paragraph Style: {0}.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph Structure Le&amp;vels.
        /// </summary>
        internal static string Item_Format_ParagraphStructureLevels_Text {
            get {
                return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh&amp;ape....
        /// </summary>
        internal static string Item_Format_Shape_Text {
            get {
                return ResourceManager.GetString("Item_Format_Shape_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Styles....
        /// </summary>
        internal static string Item_Format_Styles_Text {
            get {
                return ResourceManager.GetString("Item_Format_Styles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabl&amp;e of Contents....
        /// </summary>
        internal static string Item_Format_TableOfContents_Text {
            get {
                return ResourceManager.GetString("Item_Format_TableOfContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tabs....
        /// </summary>
        internal static string Item_Format_Tabs_Text {
            get {
                return ResourceManager.GetString("Item_Format_Tabs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;ormat.
        /// </summary>
        internal static string Item_Format_Text {
            get {
                return ResourceManager.GetString("Item_Format_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Te&amp;xt Frame....
        /// </summary>
        internal static string Item_Format_TextFrame_Text {
            get {
                return ResourceManager.GetString("Item_Format_TextFrame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Barcode.
        /// </summary>
        internal static string Item_Insert_Barcode_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Barcode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete....
        /// </summary>
        internal static string Item_Insert_Bookmark_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Bookmark_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert....
        /// </summary>
        internal static string Item_Insert_Bookmark_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Bookmark_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boo&amp;kmark.
        /// </summary>
        internal static string Item_Insert_Bookmark_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Bookmark_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;More Columns....
        /// </summary>
        internal static string Item_Insert_Columns_MoreColumns_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_MoreColumns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;One.
        /// </summary>
        internal static string Item_Insert_Columns_One_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_One_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Columns.
        /// </summary>
        internal static string Item_Insert_Columns_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Two.
        /// </summary>
        internal static string Item_Insert_Columns_Two_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Columns_Two_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File....
        /// </summary>
        internal static string Item_Insert_File_Text {
            get {
                return ResourceManager.GetString("Item_Insert_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Item_Insert_Footer_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Footer_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string Item_Insert_Footer_Remove_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Footer_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F&amp;ooter.
        /// </summary>
        internal static string Item_Insert_Footer_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Footer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Check Box.
        /// </summary>
        internal static string Item_Insert_FormField_CheckBox_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_CheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ombo Box.
        /// </summary>
        internal static string Item_Insert_FormField_ComboBox_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_ComboBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;ate Form Field.
        /// </summary>
        internal static string Item_Insert_FormField_DateFormField_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_DateFormField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&amp;elete.
        /// </summary>
        internal static string Item_Insert_FormField_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Drop-Down List.
        /// </summary>
        internal static string Item_Insert_FormField_DropDownList_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_DropDownList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fo&amp;rm Field.
        /// </summary>
        internal static string Item_Insert_FormField_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Text Form Field.
        /// </summary>
        internal static string Item_Insert_FormField_TextFormField_Text {
            get {
                return ResourceManager.GetString("Item_Insert_FormField_TextFormField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Item_Insert_Header_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Header_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string Item_Insert_Header_Remove_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Header_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Header.
        /// </summary>
        internal static string Item_Insert_Header_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyp&amp;erlink....
        /// </summary>
        internal static string Item_Insert_Hyperlink_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Hyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Image....
        /// </summary>
        internal static string Item_Insert_Image_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Image_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Columns.
        /// </summary>
        internal static string Item_Insert_PageBreaks_Column_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Page.
        /// </summary>
        internal static string Item_Insert_PageBreaks_Page_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_Page_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;age Break.
        /// </summary>
        internal static string Item_Insert_PageBreaks_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Text Wrapping.
        /// </summary>
        internal static string Item_Insert_PageBreaks_TextWrapping_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageBreaks_TextWrapping_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Item_Insert_PageNumber_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageNumber_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Item_Insert_PageNumber_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageNumber_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Page Number.
        /// </summary>
        internal static string Item_Insert_PageNumber_Text {
            get {
                return ResourceManager.GetString("Item_Insert_PageNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Continuous.
        /// </summary>
        internal static string Item_Insert_SectionBreaks_Continuous_Text {
            get {
                return ResourceManager.GetString("Item_Insert_SectionBreaks_Continuous_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next Page.
        /// </summary>
        internal static string Item_Insert_SectionBreaks_NextPage_Text {
            get {
                return ResourceManager.GetString("Item_Insert_SectionBreaks_NextPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectio&amp;n Break.
        /// </summary>
        internal static string Item_Insert_SectionBreaks_Text {
            get {
                return ResourceManager.GetString("Item_Insert_SectionBreaks_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Basic Shapes.
        /// </summary>
        internal static string Item_Insert_Shape_BasicShapes_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_BasicShapes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block &amp;Arrows.
        /// </summary>
        internal static string Item_Insert_Shape_BlockArrows_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_BlockArrows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Callouts.
        /// </summary>
        internal static string Item_Insert_Shape_Callouts_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Callouts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Drawing Canvas.
        /// </summary>
        internal static string Item_Insert_Shape_DrawingCanvas_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_DrawingCanvas_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Equation Shapes.
        /// </summary>
        internal static string Item_Insert_Shape_EquationShapes_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_EquationShapes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Flowchart.
        /// </summary>
        internal static string Item_Insert_Shape_Flowchart_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Flowchart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Lines.
        /// </summary>
        internal static string Item_Insert_Shape_Lines_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Lines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rectangles.
        /// </summary>
        internal static string Item_Insert_Shape_Rectangles_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Rectangles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Stars and Banners.
        /// </summary>
        internal static string Item_Insert_Shape_StarsAndBanners_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_StarsAndBanners_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Shape.
        /// </summary>
        internal static string Item_Insert_Shape_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Shape_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sy&amp;mbol....
        /// </summary>
        internal static string Item_Insert_Symbol_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Symbol_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Item_Insert_TableOfContents_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Item_Insert_TableOfContents_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab&amp;le of Contents.
        /// </summary>
        internal static string Item_Insert_TableOfContents_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Update.
        /// </summary>
        internal static string Item_Insert_TableOfContents_Update_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TableOfContents_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Item_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Text Frame.
        /// </summary>
        internal static string Item_Insert_TextFrame_Text {
            get {
                return ResourceManager.GetString("Item_Insert_TextFrame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ells.
        /// </summary>
        internal static string Item_Table_Delete_Cells_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Cells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Columns.
        /// </summary>
        internal static string Item_Table_Delete_Columns_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Columns_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rows.
        /// </summary>
        internal static string Item_Table_Delete_Rows_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Rows_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Table.
        /// </summary>
        internal static string Item_Table_Delete_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Item_Table_Delete_Text {
            get {
                return ResourceManager.GetString("Item_Table_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;A1 Reference Style.
        /// </summary>
        internal static string Item_Table_Formulas_A1ReferenceStyle_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_A1ReferenceStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Automatic &amp;Calculation.
        /// </summary>
        internal static string Item_Table_Formulas_AutomaticCalculation_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_AutomaticCalculation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit Formula....
        /// </summary>
        internal static string Item_Table_Formulas_EditFormula_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_EditFormula_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;R1C1 Reference Style.
        /// </summary>
        internal static string Item_Table_Formulas_R1C1ReferenceStyle_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_R1C1ReferenceStyle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Formulas.
        /// </summary>
        internal static string Item_Table_Formulas_Text {
            get {
                return ResourceManager.GetString("Item_Table_Formulas_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column To The &amp;Left.
        /// </summary>
        internal static string Item_Table_Insert_ColumnToTheLeft_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_ColumnToTheLeft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column To The &amp;Right.
        /// </summary>
        internal static string Item_Table_Insert_ColumnToTheRight_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_ColumnToTheRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row &amp;Above.
        /// </summary>
        internal static string Item_Table_Insert_RowAbove_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_RowAbove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row &amp;Below.
        /// </summary>
        internal static string Item_Table_Insert_RowBelow_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_RowBelow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Table....
        /// </summary>
        internal static string Item_Table_Insert_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Insert.
        /// </summary>
        internal static string Item_Table_Insert_Text {
            get {
                return ResourceManager.GetString("Item_Table_Insert_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Merge Cells.
        /// </summary>
        internal static string Item_Table_MergeCells_Text {
            get {
                return ResourceManager.GetString("Item_Table_MergeCells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Properties....
        /// </summary>
        internal static string Item_Table_Properties_Text {
            get {
                return ResourceManager.GetString("Item_Table_Properties_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ell.
        /// </summary>
        internal static string Item_Table_Select_Cell_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Cell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Column.
        /// </summary>
        internal static string Item_Table_Select_Column_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Column_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Row.
        /// </summary>
        internal static string Item_Table_Select_Row_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Row_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Table.
        /// </summary>
        internal static string Item_Table_Select_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Select.
        /// </summary>
        internal static string Item_Table_Select_Text {
            get {
                return ResourceManager.GetString("Item_Table_Select_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split &amp;Cells.
        /// </summary>
        internal static string Item_Table_SplitCells_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitCells_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Above.
        /// </summary>
        internal static string Item_Table_SplitTable_Above_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitTable_Above_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Below.
        /// </summary>
        internal static string Item_Table_SplitTable_Below_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitTable_Below_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split &amp;Table.
        /// </summary>
        internal static string Item_Table_SplitTable_Text {
            get {
                return ResourceManager.GetString("Item_Table_SplitTable_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Table.
        /// </summary>
        internal static string Item_Table_Text {
            get {
                return ResourceManager.GetString("Item_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B&amp;ookmark Markers.
        /// </summary>
        internal static string Item_View_BookmarkMarkers_Text {
            get {
                return ResourceManager.GetString("Item_View_BookmarkMarkers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Button Bar.
        /// </summary>
        internal static string Item_View_ButtonBar_Text {
            get {
                return ResourceManager.GetString("Item_View_ButtonBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Always.
        /// </summary>
        internal static string Item_View_Comments_Always_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Always_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Current.
        /// </summary>
        internal static string Item_View_Comments_Current_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Current_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Never.
        /// </summary>
        internal static string Item_View_Comments_Never_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Never_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co&amp;mments.
        /// </summary>
        internal static string Item_View_Comments_Text {
            get {
                return ResourceManager.GetString("Item_View_Comments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Control Chars.
        /// </summary>
        internal static string Item_View_ControlChars_Text {
            get {
                return ResourceManager.GetString("Item_View_ControlChars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Draft.
        /// </summary>
        internal static string Item_View_Draft_Text {
            get {
                return ResourceManager.GetString("Item_View_Draft_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dra&amp;wing Marker Lines.
        /// </summary>
        internal static string Item_View_DrawingMarkerLines_Text {
            get {
                return ResourceManager.GetString("Item_View_DrawingMarkerLines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Always.
        /// </summary>
        internal static string Item_View_EditableRegions_Always_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Always_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Current.
        /// </summary>
        internal static string Item_View_EditableRegions_Current_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Current_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Never.
        /// </summary>
        internal static string Item_View_EditableRegions_Never_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Never_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Editiable Regions.
        /// </summary>
        internal static string Item_View_EditableRegions_Text {
            get {
                return ResourceManager.GetString("Item_View_EditableRegions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Horizontal Ruler.
        /// </summary>
        internal static string Item_View_HorizontalRuler_Text {
            get {
                return ResourceManager.GetString("Item_View_HorizontalRuler_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Page Layout.
        /// </summary>
        internal static string Item_View_PageLayout_Text {
            get {
                return ResourceManager.GetString("Item_View_PageLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Right to Left Layout.
        /// </summary>
        internal static string Item_View_RightToLeftLayout_Text {
            get {
                return ResourceManager.GetString("Item_View_RightToLeftLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Bar.
        /// </summary>
        internal static string Item_View_StatusBar_Text {
            get {
                return ResourceManager.GetString("Item_View_StatusBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Table Gridlines.
        /// </summary>
        internal static string Item_View_TableGridlines_Text {
            get {
                return ResourceManager.GetString("Item_View_TableGridlines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string Item_View_Text {
            get {
                return ResourceManager.GetString("Item_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text &amp;Frame Marker Lines.
        /// </summary>
        internal static string Item_View_TextFrameMarkerLines_Text {
            get {
                return ResourceManager.GetString("Item_View_TextFrameMarkerLines_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tr&amp;acked Changes.
        /// </summary>
        internal static string Item_View_TrackedChanges_Text {
            get {
                return ResourceManager.GetString("Item_View_TrackedChanges_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Vertical Ruler.
        /// </summary>
        internal static string Item_View_VerticalRuler_Text {
            get {
                return ResourceManager.GetString("Item_View_VerticalRuler_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        internal static string Item_View_Zoom_Factor_Text {
            get {
                return ResourceManager.GetString("Item_View_Zoom_Factor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zoom.
        /// </summary>
        internal static string Item_View_Zoom_Text {
            get {
                return ResourceManager.GetString("Item_View_Zoom_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Text Control Words.
        /// </summary>
        internal static string MainWindow_Caption_Product {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [untitled].
        /// </summary>
        internal static string MainWindow_Caption_Untitled {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string MessageBox_AddComment_Error_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        internal static string MessageBox_AddComment_Error_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string MessageBox_AddComment_NoSelection_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a part of the document to add a comment about it..
        /// </summary>
        internal static string MessageBox_AddComment_NoSelection_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string MessageBox_AddComment_PositionInvalid_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        /// </summary>
        internal static string MessageBox_AddComment_PositionInvalid_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string MessageBox_AddComment_SelectionTooComplex_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        /// </summary>
        internal static string MessageBox_AddComment_SelectionTooComplex_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        internal static string MessageBox_AddEditableRegion_Error_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        internal static string MessageBox_AddEditableRegion_Error_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        internal static string MessageBox_AddEditableRegion_NoSelection_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select a part of the document and then choose the user who can freely edit it..
        /// </summary>
        internal static string MessageBox_AddEditableRegion_NoSelection_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        internal static string MessageBox_AddEditableRegion_PositionInvalid_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editable region wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        /// </summary>
        internal static string MessageBox_AddEditableRegion_PositionInvalid_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editable Regions.
        /// </summary>
        internal static string MessageBox_AddEditableRegion_SelectionTooComplex_Caption {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editable region wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        /// </summary>
        internal static string MessageBox_AddEditableRegion_SelectionTooComplex_Text {
            get {
                return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception is thrown:
        ///	
        ///&quot;{0}&quot;
        ///
        ///To get help, please visit the Text Control Support at www.textcontrol.com..
        /// </summary>
        internal static string MessageBox_Application_ThreadException_Text {
            get {
                return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Form Layout.
        /// </summary>
        internal static string MessageBox_ChangeFormLayout_Caption {
            get {
                return ResourceManager.GetString("MessageBox_ChangeFormLayout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. 
        ///Click OK to restart or Cancel to not restart the program..
        /// </summary>
        internal static string MessageBox_ChangeFormLayout_Text {
            get {
                return ResourceManager.GetString("MessageBox_ChangeFormLayout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hyperlink.
        /// </summary>
        internal static string MessageBox_OpenHyperlink_CouldNotOpenLink_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        /// </summary>
        internal static string MessageBox_OpenHyperlink_CouldNotOpenLink_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open linked File.
        /// </summary>
        internal static string MessageBox_OpenHyperlink_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MessageBox_OpenHyperlink_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent File.
        /// </summary>
        internal static string MessageBox_OpenRecentFile_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        /// </summary>
        internal static string MessageBox_OpenRecentFile_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        internal static string MessageBox_PasswordDialog_IncorrectPassword_Caption {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is incorrect..
        /// </summary>
        internal static string MessageBox_PasswordDialog_IncorrectPassword_Text {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentBeforeRestart_Left {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentBeforeRestart_Right {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to &apos;{2}&apos; were not saved.
        ///Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentBeforeRestart_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to the document were not saved.
        ///Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentBeforeRestart_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Of Contents.
        /// </summary>
        internal static string MessageBox_UpdateTableOfContents_NoContents_Caption {
            get {
                return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No table of contents entries found..
        /// </summary>
        internal static string MessageBox_UpdateTableOfContents_NoContents_Text {
            get {
                return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string MessageBox_UserAccess_SignOut_Caption {
            get {
                return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was successfully signed out..
        /// </summary>
        internal static string MessageBox_UserAccess_SignOut_Text {
            get {
                return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By deleting the account, the current user will be signed out. Click OK to proceed or Cancel to not delete the account..
        /// </summary>
        internal static string MessageBox_UserAccessDialogDeleteAccount_Text {
            get {
                return ResourceManager.GetString("MessageBox_UserAccessDialogDeleteAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password does not match the given user&apos;s password..
        /// </summary>
        internal static string MessageBox_UserAccessDialogIncorrectPassword_Text {
            get {
                return ResourceManager.GetString("MessageBox_UserAccessDialogIncorrectPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Tracked Changes.
        /// </summary>
        internal static string Method_SetTrackedChangesHighlightMode_HideTrackedChanges {
            get {
                return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HideTrackedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Tracked Changes.
        /// </summary>
        internal static string Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges {
            get {
                return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordDialog_Caption {
            get {
                return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password to open the document..
        /// </summary>
        internal static string PasswordDialog_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PasswordDialog_OK {
            get {
                return ResourceManager.GetString("PasswordDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string PasswordDialog_Password {
            get {
                return ResourceManager.GetString("PasswordDialog_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        /// </summary>
        internal static string PasswordDialog_ProtectedDocument {
            get {
                return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column: .
        /// </summary>
        internal static string StatusBar_Column {
            get {
                return ResourceManager.GetString("StatusBar_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: .
        /// </summary>
        internal static string StatusBar_Line {
            get {
                return ResourceManager.GetString("StatusBar_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: .
        /// </summary>
        internal static string StatusBar_Page {
            get {
                return ResourceManager.GetString("StatusBar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: .
        /// </summary>
        internal static string StatusBar_Section {
            get {
                return ResourceManager.GetString("StatusBar_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        internal static string UserAccessDialog_AccountSettings_Caption {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Confirm Password:.
        /// </summary>
        internal static string UserAccessDialog_AccountSettings_ConfirmPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete Account.
        /// </summary>
        internal static string UserAccessDialog_AccountSettings_Delete {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Password:.
        /// </summary>
        internal static string UserAccessDialog_AccountSettings_NewPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Old Password:.
        /// </summary>
        internal static string UserAccessDialog_AccountSettings_OldPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_AccountSettings_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string UserAccessDialog_Cancel {
            get {
                return ResourceManager.GetString("UserAccessDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New User Account.
        /// </summary>
        internal static string UserAccessDialog_CreateAccount_Caption {
            get {
                return ResourceManager.GetString("UserAccessDialog_CreateAccount_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Confirm Password:.
        /// </summary>
        internal static string UserAccessDialog_CreateAccount_ConfirmPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_CreateAccount_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Password:.
        /// </summary>
        internal static string UserAccessDialog_CreateAccount_NewPassword {
            get {
                return ResourceManager.GetString("UserAccessDialog_CreateAccount_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string UserAccessDialog_OK {
            get {
                return ResourceManager.GetString("UserAccessDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string UserAccessDialog_SignIn_Caption {
            get {
                return ResourceManager.GetString("UserAccessDialog_SignIn_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string UserAccessDialog_SignIn_Password {
            get {
                return ResourceManager.GetString("UserAccessDialog_SignIn_Password", resourceCulture);
            }
        }
    }
}
