//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TXTextControl.Words.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TXTextControl.Words.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this Sample.
        /// </summary>
        internal static string AboutButton_ToolTip_Description {
            get {
                return ResourceManager.GetString("AboutButton_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        internal static string ApplicationMenu_ResentFiles {
            get {
                return ResourceManager.GetString("ApplicationMenu_ResentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Frame Name….
        /// </summary>
        internal static string ContextMenu_FameName {
            get {
                return ResourceManager.GetString("ContextMenu_FameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ContextMenu_FrameNameDialog_Cancel {
            get {
                return ResourceManager.GetString("ContextMenu_FrameNameDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Frame Name.
        /// </summary>
        internal static string ContextMenu_FrameNameDialog_Caption {
            get {
                return ResourceManager.GetString("ContextMenu_FrameNameDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Frame name:.
        /// </summary>
        internal static string ContextMenu_FrameNameDialog_Label {
            get {
                return ResourceManager.GetString("ContextMenu_FrameNameDialog_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ContextMenu_FrameNameDialog_OK {
            get {
                return ResourceManager.GetString("ContextMenu_FrameNameDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Tools.
        /// </summary>
        internal static string ContextualTabGroup_ChartTools {
            get {
                return ResourceManager.GetString("ContextualTabGroup_ChartTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Tools.
        /// </summary>
        internal static string ContextualTabGroup_FrameTools {
            get {
                return ResourceManager.GetString("ContextualTabGroup_FrameTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tools.
        /// </summary>
        internal static string ContextualTabGroup_TableTools {
            get {
                return ResourceManager.GetString("ContextualTabGroup_TableTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Text Control Words.
        /// </summary>
        internal static string MainWindow_Caption_Product {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [untitled].
        /// </summary>
        internal static string MainWindow_Caption_Untitled {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception is thrown:
        ///	
        ///&quot;{0}&quot;
        ///
        ///To get help, please visit the Text Control Support at www.textcontrol.com..
        /// </summary>
        internal static string MessageBox_Application_ThreadException_Text {
            get {
                return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hyperlink.
        /// </summary>
        internal static string MessageBox_OpenHyperlink_CouldNotOpenLink_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        /// </summary>
        internal static string MessageBox_OpenHyperlink_CouldNotOpenLink_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open linked File.
        /// </summary>
        internal static string MessageBox_OpenHyperlink_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MessageBox_OpenHyperlink_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent File.
        /// </summary>
        internal static string MessageBox_OpenRecentFile_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        /// </summary>
        internal static string MessageBox_OpenRecentFile_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        internal static string MessageBox_PasswordDialog_IncorrectPassword_Caption {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is incorrect..
        /// </summary>
        internal static string MessageBox_PasswordDialog_IncorrectPassword_Text {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordDialog_Caption {
            get {
                return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password to open the document..
        /// </summary>
        internal static string PasswordDialog_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PasswordDialog_OK {
            get {
                return ResourceManager.GetString("PasswordDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string PasswordDialog_Password {
            get {
                return ResourceManager.GetString("PasswordDialog_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        /// </summary>
        internal static string PasswordDialog_ProtectedDocument {
            get {
                return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column: .
        /// </summary>
        internal static string StatusBar_Column {
            get {
                return ResourceManager.GetString("StatusBar_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: .
        /// </summary>
        internal static string StatusBar_Line {
            get {
                return ResourceManager.GetString("StatusBar_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: .
        /// </summary>
        internal static string StatusBar_Page {
            get {
                return ResourceManager.GetString("StatusBar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: .
        /// </summary>
        internal static string StatusBar_Section {
            get {
                return ResourceManager.GetString("StatusBar_Section", resourceCulture);
            }
        }
    }
}
