//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TXTextControl.Words.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TXTextControl.Words.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this Sample.
        /// </summary>
        internal static string AboutButton_ToolTip_Description {
            get {
                return ResourceManager.GetString("AboutButton_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sample Template.
        /// </summary>
        internal static string ApplicationMenu_OpenSampleTemplate {
            get {
                return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string ApplicationMenu_OpenSampleTemplate_KeyTip {
            get {
                return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides three sample templates that can be combined with the reporting tab&apos;s database sample to show a typical merge process..
        /// </summary>
        internal static string ApplicationMenu_OpenSampleTemplate_ToolTip_Description {
            get {
                return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sample Template.
        /// </summary>
        internal static string ApplicationMenu_OpenSampleTemplate_ToolTip_Title {
            get {
                return ResourceManager.GetString("ApplicationMenu_OpenSampleTemplate_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        internal static string ApplicationMenu_ResentFiles {
            get {
                return ResourceManager.GetString("ApplicationMenu_ResentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Invoice Template.
        /// </summary>
        internal static string ApplicationMenu_SampleInvoiceTemplate {
            get {
                return ResourceManager.GetString("ApplicationMenu_SampleInvoiceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string ApplicationMenu_SampleInvoiceTemplate_KeyTip {
            get {
                return ResourceManager.GetString("ApplicationMenu_SampleInvoiceTemplate_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Packing List Template.
        /// </summary>
        internal static string ApplicationMenu_SamplePackingListTemplate {
            get {
                return ResourceManager.GetString("ApplicationMenu_SamplePackingListTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string ApplicationMenu_SamplePackingListTemplate_KeyTip {
            get {
                return ResourceManager.GetString("ApplicationMenu_SamplePackingListTemplate_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Shipping Label Template.
        /// </summary>
        internal static string ApplicationMenu_SampleShippingLabelTemplate {
            get {
                return ResourceManager.GetString("ApplicationMenu_SampleShippingLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string ApplicationMenu_SampleShippingLabelTemplate_KeyTip {
            get {
                return ResourceManager.GetString("ApplicationMenu_SampleShippingLabelTemplate_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Tools.
        /// </summary>
        internal static string ContextualTabGroup_ChartTools {
            get {
                return ResourceManager.GetString("ContextualTabGroup_ChartTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Tools.
        /// </summary>
        internal static string ContextualTabGroup_FrameTools {
            get {
                return ResourceManager.GetString("ContextualTabGroup_FrameTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string ContextualTabGroup_Reporting {
            get {
                return ResourceManager.GetString("ContextualTabGroup_Reporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Tools.
        /// </summary>
        internal static string ContextualTabGroup_TableTools {
            get {
                return ResourceManager.GetString("ContextualTabGroup_TableTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Merge Result....
        /// </summary>
        internal static string ExportMergeResult {
            get {
                return ResourceManager.GetString("ExportMergeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ExportMergeResult_KeyTip {
            get {
                return ResourceManager.GetString("ExportMergeResult_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a dialog to export the merge result..
        /// </summary>
        internal static string ExportMergeResult_ToolTip_Description {
            get {
                return ResourceManager.GetString("ExportMergeResult_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Merge Result.
        /// </summary>
        internal static string ExportMergeResult_ToolTip_Title {
            get {
                return ResourceManager.GetString("ExportMergeResult_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ExportMergeResultDialog_Cancel {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Merge Result.
        /// </summary>
        internal static string ExportMergeResultDialog_Caption {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Directory:.
        /// </summary>
        internal static string ExportMergeResultDialog_Directory {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &amp;Prefix:.
        /// </summary>
        internal static string ExportMergeResultDialog_FilePrefix {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_FilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Format:.
        /// </summary>
        internal static string ExportMergeResultDialog_Format {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word 97-2003 (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_DOC {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_DOCX {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_DOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertext Markup Language (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_HTML {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_PDF {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich Text Format (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_RTF {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Text Control Format (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_TX {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_TX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain Text (*{0}).
        /// </summary>
        internal static string ExportMergeResultDialog_Format_TXT {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_Format_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ExportMergeResultDialog_OK {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open directory after export.
        /// </summary>
        internal static string ExportMergeResultDialog_openDirectory {
            get {
                return ResourceManager.GetString("ExportMergeResultDialog_openDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TX Text Control Words.
        /// </summary>
        internal static string MainWindow_Caption_Product {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [untitled].
        /// </summary>
        internal static string MainWindow_Caption_Untitled {
            get {
                return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string Merge_KeyTip {
            get {
                return ResourceManager.GetString("Merge_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge and Export.
        /// </summary>
        internal static string MergeAndExport {
            get {
                return ResourceManager.GetString("MergeAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string MergeAndExport_KeyTip {
            get {
                return ResourceManager.GetString("MergeAndExport_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the merge process and opens the &apos;Results&apos; tab to show and export the created documents..
        /// </summary>
        internal static string MergeAndExport_ToolTip_Description {
            get {
                return ResourceManager.GetString("MergeAndExport_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge and Export.
        /// </summary>
        internal static string MergeAndExport_ToolTip_Title {
            get {
                return ResourceManager.GetString("MergeAndExport_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        internal static string MergeAndWaitDialog_Caption {
            get {
                return ResourceManager.GetString("MergeAndWaitDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging.....
        /// </summary>
        internal static string MergeAndWaitDialog_Merging {
            get {
                return ResourceManager.GetString("MergeAndWaitDialog_Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Results  .
        /// </summary>
        internal static string MergeResultsTab {
            get {
                return ResourceManager.GetString("MergeResultsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MergeResultsTab_Exit {
            get {
                return ResourceManager.GetString("MergeResultsTab_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string MergeResultsTab_Exit_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_Exit_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes the &apos;Result&apos; tab..
        /// </summary>
        internal static string MergeResultsTab_Exit_ToolTip_Description {
            get {
                return ResourceManager.GetString("MergeResultsTab_Exit_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MergeResultsTab_Exit_ToolTip_Title {
            get {
                return ResourceManager.GetString("MergeResultsTab_Exit_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string MergeResultsTab_Export {
            get {
                return ResourceManager.GetString("MergeResultsTab_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string MergeResultsTab_Export_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_Export_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Record.
        /// </summary>
        internal static string MergeResultsTab_FirstRecord {
            get {
                return ResourceManager.GetString("MergeResultsTab_FirstRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string MergeResultsTab_FirstRecord_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_FirstRecord_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Record.
        /// </summary>
        internal static string MergeResultsTab_FirstRecord_ToolTip_Title {
            get {
                return ResourceManager.GetString("MergeResultsTab_FirstRecord_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string MergeResultsTab_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Record.
        /// </summary>
        internal static string MergeResultsTab_LastRecord {
            get {
                return ResourceManager.GetString("MergeResultsTab_LastRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string MergeResultsTab_LastRecord_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_LastRecord_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Record.
        /// </summary>
        internal static string MergeResultsTab_LastRecord_ToolTip_Title {
            get {
                return ResourceManager.GetString("MergeResultsTab_LastRecord_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        internal static string MergeResultsTab_Navigate {
            get {
                return ResourceManager.GetString("MergeResultsTab_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string MergeResultsTab_Navigate_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_Navigate_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Record.
        /// </summary>
        internal static string MergeResultsTab_NextRecord {
            get {
                return ResourceManager.GetString("MergeResultsTab_NextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string MergeResultsTab_NextRecord_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_NextRecord_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Record.
        /// </summary>
        internal static string MergeResultsTab_NextRecord_ToolTip_Title {
            get {
                return ResourceManager.GetString("MergeResultsTab_NextRecord_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Record.
        /// </summary>
        internal static string MergeResultsTab_PreviousRecord {
            get {
                return ResourceManager.GetString("MergeResultsTab_PreviousRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string MergeResultsTab_PreviousRecord_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_PreviousRecord_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Record.
        /// </summary>
        internal static string MergeResultsTab_PreviousRecord_ToolTip_Title {
            get {
                return ResourceManager.GetString("MergeResultsTab_PreviousRecord_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to record no. {0}..
        /// </summary>
        internal static string MergeResultsTab_Record_ToolTip_Description {
            get {
                return ResourceManager.GetString("MergeResultsTab_Record_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string MergeResultsTab_Result {
            get {
                return ResourceManager.GetString("MergeResultsTab_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        internal static string MergeResultsTab_Result_KeyTip {
            get {
                return ResourceManager.GetString("MergeResultsTab_Result_KeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Blocks.
        /// </summary>
        internal static string MergeSettingsDialog_Blocks {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MergeSettingsDialog_Cancel {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Settings.
        /// </summary>
        internal static string MergeSettingsDialog_Caption {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fields.
        /// </summary>
        internal static string MergeSettingsDialog_Fields {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Images.
        /// </summary>
        internal static string MergeSettingsDialog_Images {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Lines.
        /// </summary>
        internal static string MergeSettingsDialog_Lines {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge &amp;all records.
        /// </summary>
        internal static string MergeSettingsDialog_MergeAllRecords {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_MergeAllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Merge into single document.
        /// </summary>
        internal static string MergeSettingsDialog_MergeIntoSingleDocument {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_MergeIntoSingleDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Number of records:.
        /// </summary>
        internal static string MergeSettingsDialog_NumberOfRecords {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_NumberOfRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MergeSettingsDialog_OK {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string MergeSettingsDialog_Records {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty merge elements.
        /// </summary>
        internal static string MergeSettingsDialog_RemoveEmptyMergeElements {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_RemoveEmptyMergeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Trailing Whitespace.
        /// </summary>
        internal static string MergeSettingsDialog_TrailingWhitespace {
            get {
                return ResourceManager.GetString("MergeSettingsDialog_TrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception is thrown:
        ///	
        ///&quot;{0}&quot;
        ///
        ///To get help, please visit the Text Control Support at www.textcontrol.com..
        /// </summary>
        internal static string MessageBox_Application_ThreadException_Text {
            get {
                return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Results.
        /// </summary>
        internal static string MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory does not exist..
        /// </summary>
        internal static string MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_ExportMergeResultDialog_DirectoryDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Hyperlink.
        /// </summary>
        internal static string MessageBox_OpenHyperlink_CouldNotOpenLink_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        /// </summary>
        internal static string MessageBox_OpenHyperlink_CouldNotOpenLink_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open linked File.
        /// </summary>
        internal static string MessageBox_OpenHyperlink_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MessageBox_OpenHyperlink_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recent File.
        /// </summary>
        internal static string MessageBox_OpenRecentFile_FileDoesNotExist_Caption {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        /// </summary>
        internal static string MessageBox_OpenRecentFile_FileDoesNotExist_Text {
            get {
                return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        internal static string MessageBox_PasswordDialog_IncorrectPassword_Caption {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered password is incorrect..
        /// </summary>
        internal static string MessageBox_PasswordDialog_IncorrectPassword_Text {
            get {
                return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the program closes? 
        ///Click Yes to save and close, No to close without saving, or Cancel to not close..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnExit_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before a new document is created? 
        ///Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnNew_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_Caption {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_ToFile {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        ///Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        /// </summary>
        internal static string MessageBox_SaveDirtyDocumentOnOpen_Untitled {
            get {
                return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordDialog_Caption {
            get {
                return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password to open the document..
        /// </summary>
        internal static string PasswordDialog_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PasswordDialog_OK {
            get {
                return ResourceManager.GetString("PasswordDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string PasswordDialog_Password {
            get {
                return ResourceManager.GetString("PasswordDialog_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        /// </summary>
        internal static string PasswordDialog_ProtectedDocument {
            get {
                return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Sample Database.
        /// </summary>
        internal static string RibbonReportingTab_LoadSampleDatabase {
            get {
                return ResourceManager.GetString("RibbonReportingTab_LoadSampleDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a sample database..
        /// </summary>
        internal static string RibbonReportingTab_LoadSampleDatabase_ToolTip_Description {
            get {
                return ResourceManager.GetString("RibbonReportingTab_LoadSampleDatabase_ToolTip_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Sample Database.
        /// </summary>
        internal static string RibbonReportingTab_LoadSampleDatabase_ToolTip_Title {
            get {
                return ResourceManager.GetString("RibbonReportingTab_LoadSampleDatabase_ToolTip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column: .
        /// </summary>
        internal static string StatusBar_Column {
            get {
                return ResourceManager.GetString("StatusBar_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line: .
        /// </summary>
        internal static string StatusBar_Line {
            get {
                return ResourceManager.GetString("StatusBar_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page: .
        /// </summary>
        internal static string StatusBar_Page {
            get {
                return ResourceManager.GetString("StatusBar_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: .
        /// </summary>
        internal static string StatusBar_Section {
            get {
                return ResourceManager.GetString("StatusBar_Section", resourceCulture);
            }
        }
    }
}
